# Generated by Django 5.2.3 on 2026-01-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_user_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
